# Generated by Django 5.2.16 on 2026-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tax_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
